### ISSUE TITLE
No readme 

### ISSUE THREAD

**Issue by MaximilianJugendForscht** [OMGtechy/Countdown#1]
There is no readme,  so I catt really know what this program is all about (im linuxer4fun from devRant)

**Comment by OMGtechy** [comment]
Thanks!

Take a look at the TV show "Countdown" for some context.
This was something I hacked together during the advert break so I could work out the solution to an anagram. One flaw it has though is that it only finds anagrams that use all the letters, ignoring those that use less. That is something you're welcome to fix!

I'll write a README and push it sometime tomorrow hopefully :)

**Comment by MaximilianJugendForscht** [comment]
Ok gonna figure out am algorythm 4 it :)

Outlook for Android<https://aka.ms/ghei36> herunterladen



On Sun, Dec 11, 2016 at 2:02 AM +0100, "Joshua Gerrard" <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks!

Take a look at the TV show "Countdown" for some context.
This was something I hacked together during the advert break so I could work out the solution to an anagram. One flaw it has though is that it only finds anagrams that use all the letters, ignoring those that use less. That is something you're welcome to fix!

I'll write a README and push it sometime tomorrow hopefully :)

-
